### ISSUE TITLE
Rebase to v1.10.18 version of vdb geth

### ISSUE THREAD

**Issue by i-norden** [vulcanize/migration-tools#16]
Child of https://github.com/vulcanize/go-ethereum/issues/231

- [x] Release that uses the new v1.10.18-statediff-3.2.1 release of vdb geth (off of https://github.com/vulcanize/migration-tools/tree/release-v1.1.3)

**Comment by abdulrabbani00** [comment]
Tabling this for the time being. Running into many issues, will work on remaining repos and circle back.

**Comment by abdulrabbani00** [comment]
Final: https://github.com/vulcanize/migration-tools/releases/tag/v1.1.4
